
时间：2016-12-29 19:43:51,039 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\zfw\bw\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：11411 
System.Exception: {"fg":"3","x":"4","y":"8","l":"4"} ---> System.Net.WebException: 未能解析此远程名称: 't3.tianditu.com'
   在 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   在 System.Net.WebClient.DownloadData(Uri address)
   在 System.Net.WebClient.DownloadData(String address)
   在 X.App.Views.tiler.tdt.GetResponse() 位置 D:\Pro\ytgis\src\Yt.Gis\X.App\Views\tiler\tdt.cs:行号 36
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\ytgis\src\Yt.Gis\X.Web\XApp.cs:行号 27
   --- 内部异常堆栈跟踪的结尾 ---

时间：2016-12-29 19:43:51,040 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\zfw\bw\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：11412 
System.Exception: {"fg":"3","x":"0","y":"1","l":"2"} ---> System.Net.WebException: 未能解析此远程名称: 't3.tianditu.com'
   在 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   在 System.Net.WebClient.DownloadData(Uri address)
   在 System.Net.WebClient.DownloadData(String address)
   在 X.App.Views.tiler.tdt.GetResponse() 位置 D:\Pro\ytgis\src\Yt.Gis\X.App\Views\tiler\tdt.cs:行号 36
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\ytgis\src\Yt.Gis\X.Web\XApp.cs:行号 27
   --- 内部异常堆栈跟踪的结尾 ---

时间：2016-12-29 19:43:51,040 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\zfw\bw\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：11412 
System.Exception: {"fg":"3","x":"2","y":"0","l":"2"} ---> System.Net.WebException: 未能解析此远程名称: 't3.tianditu.com'
   在 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   在 System.Net.WebClient.DownloadData(Uri address)
   在 System.Net.WebClient.DownloadData(String address)
   在 X.App.Views.tiler.tdt.GetResponse() 位置 D:\Pro\ytgis\src\Yt.Gis\X.App\Views\tiler\tdt.cs:行号 36
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\ytgis\src\Yt.Gis\X.Web\XApp.cs:行号 27
   --- 内部异常堆栈跟踪的结尾 ---

时间：2016-12-29 19:43:51,039 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\zfw\bw\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：11411 
System.Exception: {"fg":"3","x":"2","y":"3","l":"2"} ---> System.Net.WebException: 未能解析此远程名称: 't3.tianditu.com'
   在 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   在 System.Net.WebClient.DownloadData(Uri address)
   在 System.Net.WebClient.DownloadData(String address)
   在 X.App.Views.tiler.tdt.GetResponse() 位置 D:\Pro\ytgis\src\Yt.Gis\X.App\Views\tiler\tdt.cs:行号 36
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\ytgis\src\Yt.Gis\X.Web\XApp.cs:行号 27
   --- 内部异常堆栈跟踪的结尾 ---

时间：2016-12-29 19:43:51,039 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\zfw\bw\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：11411 
System.Exception: {"fg":"3","x":"4","y":"5","l":"4"} ---> System.Net.WebException: 未能解析此远程名称: 't3.tianditu.com'
   在 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   在 System.Net.WebClient.DownloadData(Uri address)
   在 System.Net.WebClient.DownloadData(String address)
   在 X.App.Views.tiler.tdt.GetResponse() 位置 D:\Pro\ytgis\src\Yt.Gis\X.App\Views\tiler\tdt.cs:行号 36
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\ytgis\src\Yt.Gis\X.Web\XApp.cs:行号 27
   --- 内部异常堆栈跟踪的结尾 ---

时间：2016-12-29 19:43:51,039 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\zfw\bw\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：11411 
System.Exception: {"fg":"3","x":"2","y":"6","l":"4"} ---> System.Net.WebException: 未能解析此远程名称: 't3.tianditu.com'
   在 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   在 System.Net.WebClient.DownloadData(Uri address)
   在 System.Net.WebClient.DownloadData(String address)
   在 X.App.Views.tiler.tdt.GetResponse() 位置 D:\Pro\ytgis\src\Yt.Gis\X.App\Views\tiler\tdt.cs:行号 36
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\ytgis\src\Yt.Gis\X.Web\XApp.cs:行号 27
   --- 内部异常堆栈跟踪的结尾 ---

时间：2016-12-29 19:43:51,039 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\zfw\bw\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：11411 
System.Exception: {"fg":"3","x":"2","y":"6","l":"4"} ---> System.Net.WebException: 未能解析此远程名称: 't3.tianditu.com'
   在 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   在 System.Net.WebClient.DownloadData(Uri address)
   在 System.Net.WebClient.DownloadData(String address)
   在 X.App.Views.tiler.tdt.GetResponse() 位置 D:\Pro\ytgis\src\Yt.Gis\X.App\Views\tiler\tdt.cs:行号 36
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\ytgis\src\Yt.Gis\X.Web\XApp.cs:行号 27
   --- 内部异常堆栈跟踪的结尾 ---

时间：2016-12-29 19:43:51,039 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\zfw\bw\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：11411 
System.Exception: {"fg":"3","x":"4","y":"5","l":"4"} ---> System.Net.WebException: 未能解析此远程名称: 't3.tianditu.com'
   在 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   在 System.Net.WebClient.DownloadData(Uri address)
   在 System.Net.WebClient.DownloadData(String address)
   在 X.App.Views.tiler.tdt.GetResponse() 位置 D:\Pro\ytgis\src\Yt.Gis\X.App\Views\tiler\tdt.cs:行号 36
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\ytgis\src\Yt.Gis\X.Web\XApp.cs:行号 27
   --- 内部异常堆栈跟踪的结尾 ---

时间：2016-12-29 19:43:51,039 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\zfw\bw\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：11411 
System.Exception: {"fg":"3","x":"4","y":"8","l":"4"} ---> System.Net.WebException: 未能解析此远程名称: 't3.tianditu.com'
   在 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   在 System.Net.WebClient.DownloadData(Uri address)
   在 System.Net.WebClient.DownloadData(String address)
   在 X.App.Views.tiler.tdt.GetResponse() 位置 D:\Pro\ytgis\src\Yt.Gis\X.App\Views\tiler\tdt.cs:行号 36
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\ytgis\src\Yt.Gis\X.Web\XApp.cs:行号 27
   --- 内部异常堆栈跟踪的结尾 ---

时间：2016-12-29 19:51:43,073 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\zfw\bw\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：483444 
System.Exception: {"fg":"2","x":"1","y":"0","l":"2"} ---> System.Net.WebException: 操作超时
   在 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   在 System.Net.WebClient.DownloadData(Uri address)
   在 System.Net.WebClient.DownloadData(String address)
   在 X.App.Views.tiler.tdt.GetResponse() 位置 D:\Pro\ytgis\src\Yt.Gis\X.App\Views\tiler\tdt.cs:行号 36
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\ytgis\src\Yt.Gis\X.Web\XApp.cs:行号 27
   --- 内部异常堆栈跟踪的结尾 ---

时间：2016-12-29 20:42:00,566 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\zfw\bw\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：3500937 
System.Exception: {"fg":"3","x":"13426","y":"7019","l":"14"} ---> System.Net.WebException: 未能解析此远程名称: 't3.tianditu.com'
   在 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   在 System.Net.WebClient.DownloadData(Uri address)
   在 System.Net.WebClient.DownloadData(String address)
   在 X.App.Views.tiler.tdt.GetResponse() 位置 D:\Pro\ytgis\src\Yt.Gis\X.App\Views\tiler\tdt.cs:行号 36
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\ytgis\src\Yt.Gis\X.Web\XApp.cs:行号 27
   --- 内部异常堆栈跟踪的结尾 ---

时间：2016-12-29 21:54:02,708 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\zfw\bw\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：7823079 
System.Exception: {"fg":"4","x":"26805","y":"13965","l":"15"} ---> System.Net.WebException: 操作超时
   在 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   在 System.Net.WebClient.DownloadData(Uri address)
   在 System.Net.WebClient.DownloadData(String address)
   在 X.App.Views.tiler.tdt.GetResponse() 位置 D:\Pro\ytgis\src\Yt.Gis\X.App\Views\tiler\tdt.cs:行号 36
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\ytgis\src\Yt.Gis\X.Web\XApp.cs:行号 27
   --- 内部异常堆栈跟踪的结尾 ---

时间：2016-12-29 21:57:52,131 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\zfw\bw\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：8052503 
System.Exception: {"fg":"4","x":"11","y":"5","l":"4"} ---> System.Net.WebException: 基础连接已经关闭: 连接被意外关闭。
   在 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   在 System.Net.WebClient.DownloadData(Uri address)
   在 System.Net.WebClient.DownloadData(String address)
   在 X.App.Views.tiler.tdt.GetResponse() 位置 D:\Pro\ytgis\src\Yt.Gis\X.App\Views\tiler\tdt.cs:行号 36
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\ytgis\src\Yt.Gis\X.Web\XApp.cs:行号 27
   --- 内部异常堆栈跟踪的结尾 ---

时间：2016-12-29 21:58:13,587 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\zfw\bw\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：8073958 
System.Exception: {"fg":"1","x":"12","y":"6","l":"4"} ---> System.Net.WebException: 无法连接到远程服务器 ---> System.Net.Sockets.SocketException: 由于目标计算机积极拒绝，无法连接。 1.202.227.113:80
   在 System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   在 System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   在 System.Net.WebClient.DownloadData(Uri address)
   在 System.Net.WebClient.DownloadData(String address)
   在 X.App.Views.tiler.tdt.GetResponse() 位置 D:\Pro\ytgis\src\Yt.Gis\X.App\Views\tiler\tdt.cs:行号 36
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\ytgis\src\Yt.Gis\X.Web\XApp.cs:行号 27
   --- 内部异常堆栈跟踪的结尾 ---

时间：2016-12-29 21:58:14,732 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\zfw\bw\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：8075103 
System.Exception: {"fg":"3","x":"12","y":"4","l":"4"} ---> System.Net.WebException: 无法连接到远程服务器 ---> System.Net.Sockets.SocketException: 由于目标计算机积极拒绝，无法连接。 1.202.227.113:80
   在 System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   在 System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   在 System.Net.WebClient.DownloadData(Uri address)
   在 System.Net.WebClient.DownloadData(String address)
   在 X.App.Views.tiler.tdt.GetResponse() 位置 D:\Pro\ytgis\src\Yt.Gis\X.App\Views\tiler\tdt.cs:行号 36
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\ytgis\src\Yt.Gis\X.Web\XApp.cs:行号 27
   --- 内部异常堆栈跟踪的结尾 ---
