
时间：2017-01-01 15:31:59,326 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\zfw\bw\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：91511608 
System.Exception: {"fg":"1","x":"12","y":"6","l":"4"} ---> System.Net.WebException: 操作超时
   在 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   在 System.Net.WebClient.DownloadData(Uri address)
   在 System.Net.WebClient.DownloadData(String address)
   在 X.App.Views.tiler.tdt.GetResponse() 位置 D:\Pro\ytgis\src\Yt.Gis\X.App\Views\tiler\tdt.cs:行号 36
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\ytgis\src\Yt.Gis\X.Web\XApp.cs:行号 27
   --- 内部异常堆栈跟踪的结尾 ---

时间：2017-01-01 16:25:12,311 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\zfw\bw\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：94704593 
System.Exception: {"fg":"5","x":"12","y":"5","l":"4"} ---> System.Net.WebException: 未能解析此远程名称: 't5.tianditu.com'
   在 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   在 System.Net.WebClient.DownloadData(Uri address)
   在 System.Net.WebClient.DownloadData(String address)
   在 X.App.Views.tiler.tdt.GetResponse() 位置 D:\Pro\ytgis\src\Yt.Gis\X.App\Views\tiler\tdt.cs:行号 36
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\ytgis\src\Yt.Gis\X.Web\XApp.cs:行号 27
   --- 内部异常堆栈跟踪的结尾 ---

时间：2017-01-01 16:25:12,311 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\zfw\bw\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：94704593 
System.Exception: {"fg":"5","x":"12","y":"5","l":"4"} ---> System.Net.WebException: 未能解析此远程名称: 't5.tianditu.com'
   在 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   在 System.Net.WebClient.DownloadData(Uri address)
   在 System.Net.WebClient.DownloadData(String address)
   在 X.App.Views.tiler.tdt.GetResponse() 位置 D:\Pro\ytgis\src\Yt.Gis\X.App\Views\tiler\tdt.cs:行号 36
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\ytgis\src\Yt.Gis\X.Web\XApp.cs:行号 27
   --- 内部异常堆栈跟踪的结尾 ---

时间：2017-01-01 16:25:12,311 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\zfw\bw\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：94704593 
System.Exception: {"fg":"5","x":"13436","y":"7021","l":"14"} ---> System.Net.WebException: 未能解析此远程名称: 't5.tianditu.com'
   在 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   在 System.Net.WebClient.DownloadData(Uri address)
   在 System.Net.WebClient.DownloadData(String address)
   在 X.App.Views.tiler.tdt.GetResponse() 位置 D:\Pro\ytgis\src\Yt.Gis\X.App\Views\tiler\tdt.cs:行号 36
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\ytgis\src\Yt.Gis\X.Web\XApp.cs:行号 27
   --- 内部异常堆栈跟踪的结尾 ---

时间：2017-01-01 16:25:12,311 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\zfw\bw\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：94704593 
System.Exception: {"fg":"5","x":"13434","y":"7022","l":"14"} ---> System.Net.WebException: 未能解析此远程名称: 't5.tianditu.com'
   在 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   在 System.Net.WebClient.DownloadData(Uri address)
   在 System.Net.WebClient.DownloadData(String address)
   在 X.App.Views.tiler.tdt.GetResponse() 位置 D:\Pro\ytgis\src\Yt.Gis\X.App\Views\tiler\tdt.cs:行号 36
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\ytgis\src\Yt.Gis\X.Web\XApp.cs:行号 27
   --- 内部异常堆栈跟踪的结尾 ---

时间：2017-01-01 16:25:12,549 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\zfw\bw\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：94704831 
System.Exception: {"fg":"2","x":"13433","y":"7021","l":"14"} ---> System.Net.WebException: 未能解析此远程名称: 't2.tianditu.com'
   在 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   在 System.Net.WebClient.DownloadData(Uri address)
   在 System.Net.WebClient.DownloadData(String address)
   在 X.App.Views.tiler.tdt.GetResponse() 位置 D:\Pro\ytgis\src\Yt.Gis\X.App\Views\tiler\tdt.cs:行号 36
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\ytgis\src\Yt.Gis\X.Web\XApp.cs:行号 27
   --- 内部异常堆栈跟踪的结尾 ---

时间：2017-01-01 16:25:12,549 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\zfw\bw\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：94704831 
System.Exception: {"fg":"2","x":"11","y":"4","l":"4"} ---> System.Net.WebException: 未能解析此远程名称: 't2.tianditu.com'
   在 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   在 System.Net.WebClient.DownloadData(Uri address)
   在 System.Net.WebClient.DownloadData(String address)
   在 X.App.Views.tiler.tdt.GetResponse() 位置 D:\Pro\ytgis\src\Yt.Gis\X.App\Views\tiler\tdt.cs:行号 36
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\ytgis\src\Yt.Gis\X.Web\XApp.cs:行号 27
   --- 内部异常堆栈跟踪的结尾 ---

时间：2017-01-01 16:25:12,551 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\zfw\bw\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：94704833 
System.Exception: {"fg":"2","x":"11","y":"4","l":"4"} ---> System.Net.WebException: 未能解析此远程名称: 't2.tianditu.com'
   在 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   在 System.Net.WebClient.DownloadData(Uri address)
   在 System.Net.WebClient.DownloadData(String address)
   在 X.App.Views.tiler.tdt.GetResponse() 位置 D:\Pro\ytgis\src\Yt.Gis\X.App\Views\tiler\tdt.cs:行号 36
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\ytgis\src\Yt.Gis\X.Web\XApp.cs:行号 27
   --- 内部异常堆栈跟踪的结尾 ---

时间：2017-01-01 16:25:12,551 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\zfw\bw\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：94704833 
System.Exception: {"fg":"2","x":"13","y":"6","l":"4"} ---> System.Net.WebException: 未能解析此远程名称: 't2.tianditu.com'
   在 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   在 System.Net.WebClient.DownloadData(Uri address)
   在 System.Net.WebClient.DownloadData(String address)
   在 X.App.Views.tiler.tdt.GetResponse() 位置 D:\Pro\ytgis\src\Yt.Gis\X.App\Views\tiler\tdt.cs:行号 36
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\ytgis\src\Yt.Gis\X.Web\XApp.cs:行号 27
   --- 内部异常堆栈跟踪的结尾 ---

时间：2017-01-01 16:25:12,556 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\zfw\bw\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：94704838 
System.Exception: {"fg":"2","x":"11","y":"7","l":"4"} ---> System.Net.WebException: 未能解析此远程名称: 't2.tianditu.com'
   在 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   在 System.Net.WebClient.DownloadData(Uri address)
   在 System.Net.WebClient.DownloadData(String address)
   在 X.App.Views.tiler.tdt.GetResponse() 位置 D:\Pro\ytgis\src\Yt.Gis\X.App\Views\tiler\tdt.cs:行号 36
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\ytgis\src\Yt.Gis\X.Web\XApp.cs:行号 27
   --- 内部异常堆栈跟踪的结尾 ---

时间：2017-01-01 16:25:12,557 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\zfw\bw\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：94704839 
System.Exception: {"fg":"2","x":"13","y":"6","l":"4"} ---> System.Net.WebException: 未能解析此远程名称: 't2.tianditu.com'
   在 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   在 System.Net.WebClient.DownloadData(Uri address)
   在 System.Net.WebClient.DownloadData(String address)
   在 X.App.Views.tiler.tdt.GetResponse() 位置 D:\Pro\ytgis\src\Yt.Gis\X.App\Views\tiler\tdt.cs:行号 36
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\ytgis\src\Yt.Gis\X.Web\XApp.cs:行号 27
   --- 内部异常堆栈跟踪的结尾 ---

时间：2017-01-01 16:25:12,558 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\zfw\bw\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：94704840 
System.Exception: {"fg":"2","x":"11","y":"7","l":"4"} ---> System.Net.WebException: 未能解析此远程名称: 't2.tianditu.com'
   在 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   在 System.Net.WebClient.DownloadData(Uri address)
   在 System.Net.WebClient.DownloadData(String address)
   在 X.App.Views.tiler.tdt.GetResponse() 位置 D:\Pro\ytgis\src\Yt.Gis\X.App\Views\tiler\tdt.cs:行号 36
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\ytgis\src\Yt.Gis\X.Web\XApp.cs:行号 27
   --- 内部异常堆栈跟踪的结尾 ---

时间：2017-01-01 16:25:12,549 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\zfw\bw\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：94704831 
System.Exception: {"fg":"2","x":"13433","y":"7024","l":"14"} ---> System.Net.WebException: 未能解析此远程名称: 't2.tianditu.com'
   在 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   在 System.Net.WebClient.DownloadData(Uri address)
   在 System.Net.WebClient.DownloadData(String address)
   在 X.App.Views.tiler.tdt.GetResponse() 位置 D:\Pro\ytgis\src\Yt.Gis\X.App\Views\tiler\tdt.cs:行号 36
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\ytgis\src\Yt.Gis\X.Web\XApp.cs:行号 27
   --- 内部异常堆栈跟踪的结尾 ---

时间：2017-01-01 16:25:12,549 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\zfw\bw\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：94704831 
System.Exception: {"fg":"2","x":"13435","y":"7023","l":"14"} ---> System.Net.WebException: 未能解析此远程名称: 't2.tianditu.com'
   在 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   在 System.Net.WebClient.DownloadData(Uri address)
   在 System.Net.WebClient.DownloadData(String address)
   在 X.App.Views.tiler.tdt.GetResponse() 位置 D:\Pro\ytgis\src\Yt.Gis\X.App\Views\tiler\tdt.cs:行号 36
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\ytgis\src\Yt.Gis\X.Web\XApp.cs:行号 27
   --- 内部异常堆栈跟踪的结尾 ---

时间：2017-01-01 16:26:41,294 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\zfw\bw\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：94793575 
System.Exception: {"fg":"3","x":"12","y":"4","l":"4"} ---> System.Net.WebException: 操作超时
   在 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   在 System.Net.WebClient.DownloadData(Uri address)
   在 System.Net.WebClient.DownloadData(String address)
   在 X.App.Views.tiler.tdt.GetResponse() 位置 D:\Pro\ytgis\src\Yt.Gis\X.App\Views\tiler\tdt.cs:行号 36
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\ytgis\src\Yt.Gis\X.Web\XApp.cs:行号 27
   --- 内部异常堆栈跟踪的结尾 ---

时间：2017-01-01 17:38:53,617 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\zfw\bw\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：99125899 
System.Exception: {"fg":"1","x":"12","y":"6","l":"4"} ---> System.Net.WebException: 未能解析此远程名称: 't1.tianditu.com'
   在 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   在 System.Net.WebClient.DownloadData(Uri address)
   在 System.Net.WebClient.DownloadData(String address)
   在 X.App.Views.tiler.tdt.GetResponse() 位置 D:\Pro\ytgis\src\Yt.Gis\X.App\Views\tiler\tdt.cs:行号 36
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\ytgis\src\Yt.Gis\X.Web\XApp.cs:行号 27
   --- 内部异常堆栈跟踪的结尾 ---

时间：2017-01-01 17:55:54,976 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\zfw\bw\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：100147258 
System.Exception: {"fg":"2","x":"11","y":"4","l":"4"} ---> System.Net.WebException: 未能解析此远程名称: 't2.tianditu.com'
   在 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   在 System.Net.WebClient.DownloadData(Uri address)
   在 System.Net.WebClient.DownloadData(String address)
   在 X.App.Views.tiler.tdt.GetResponse() 位置 D:\Pro\ytgis\src\Yt.Gis\X.App\Views\tiler\tdt.cs:行号 36
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\ytgis\src\Yt.Gis\X.Web\XApp.cs:行号 27
   --- 内部异常堆栈跟踪的结尾 ---

时间：2017-01-01 19:27:36,341 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\zfw\bw\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：105648623 
System.Exception: {"fg":"3","x":"14","y":"6","l":"4"} ---> System.Net.WebException: 未能解析此远程名称: 't3.tianditu.com'
   在 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   在 System.Net.WebClient.DownloadData(Uri address)
   在 System.Net.WebClient.DownloadData(String address)
   在 X.App.Views.tiler.tdt.GetResponse() 位置 D:\Pro\ytgis\src\Yt.Gis\X.App\Views\tiler\tdt.cs:行号 36
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\ytgis\src\Yt.Gis\X.Web\XApp.cs:行号 27
   --- 内部异常堆栈跟踪的结尾 ---

时间：2017-01-01 19:27:36,343 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\zfw\bw\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：105648625 
System.Exception: {"fg":"3","x":"12","y":"4","l":"4"} ---> System.Net.WebException: 未能解析此远程名称: 't3.tianditu.com'
   在 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   在 System.Net.WebClient.DownloadData(Uri address)
   在 System.Net.WebClient.DownloadData(String address)
   在 X.App.Views.tiler.tdt.GetResponse() 位置 D:\Pro\ytgis\src\Yt.Gis\X.App\Views\tiler\tdt.cs:行号 36
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\ytgis\src\Yt.Gis\X.Web\XApp.cs:行号 27
   --- 内部异常堆栈跟踪的结尾 ---

时间：2017-01-01 19:27:36,347 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\zfw\bw\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：105648629 
System.Exception: {"fg":"3","x":"12","y":"7","l":"4"} ---> System.Net.WebException: 未能解析此远程名称: 't3.tianditu.com'
   在 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   在 System.Net.WebClient.DownloadData(Uri address)
   在 System.Net.WebClient.DownloadData(String address)
   在 X.App.Views.tiler.tdt.GetResponse() 位置 D:\Pro\ytgis\src\Yt.Gis\X.App\Views\tiler\tdt.cs:行号 36
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\ytgis\src\Yt.Gis\X.Web\XApp.cs:行号 27
   --- 内部异常堆栈跟踪的结尾 ---

时间：2017-01-01 19:27:36,341 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\zfw\bw\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：105648623 
System.Exception: {"fg":"3","x":"13428","y":"7021","l":"14"} ---> System.Net.WebException: 未能解析此远程名称: 't3.tianditu.com'
   在 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   在 System.Net.WebClient.DownloadData(Uri address)
   在 System.Net.WebClient.DownloadData(String address)
   在 X.App.Views.tiler.tdt.GetResponse() 位置 D:\Pro\ytgis\src\Yt.Gis\X.App\Views\tiler\tdt.cs:行号 36
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\ytgis\src\Yt.Gis\X.Web\XApp.cs:行号 27
   --- 内部异常堆栈跟踪的结尾 ---

时间：2017-01-01 19:27:36,341 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\zfw\bw\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：105648623 
System.Exception: {"fg":"3","x":"13426","y":"7022","l":"14"} ---> System.Net.WebException: 未能解析此远程名称: 't3.tianditu.com'
   在 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   在 System.Net.WebClient.DownloadData(Uri address)
   在 System.Net.WebClient.DownloadData(String address)
   在 X.App.Views.tiler.tdt.GetResponse() 位置 D:\Pro\ytgis\src\Yt.Gis\X.App\Views\tiler\tdt.cs:行号 36
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\ytgis\src\Yt.Gis\X.Web\XApp.cs:行号 27
   --- 内部异常堆栈跟踪的结尾 ---

时间：2017-01-01 19:27:36,341 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\zfw\bw\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：105648623 
System.Exception: {"fg":"3","x":"12","y":"7","l":"4"} ---> System.Net.WebException: 未能解析此远程名称: 't3.tianditu.com'
   在 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   在 System.Net.WebClient.DownloadData(Uri address)
   在 System.Net.WebClient.DownloadData(String address)
   在 X.App.Views.tiler.tdt.GetResponse() 位置 D:\Pro\ytgis\src\Yt.Gis\X.App\Views\tiler\tdt.cs:行号 36
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\ytgis\src\Yt.Gis\X.Web\XApp.cs:行号 27
   --- 内部异常堆栈跟踪的结尾 ---

时间：2017-01-01 19:27:36,343 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\zfw\bw\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：105648625 
System.Exception: {"fg":"3","x":"13426","y":"7019","l":"14"} ---> System.Net.WebException: 未能解析此远程名称: 't3.tianditu.com'
   在 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   在 System.Net.WebClient.DownloadData(Uri address)
   在 System.Net.WebClient.DownloadData(String address)
   在 X.App.Views.tiler.tdt.GetResponse() 位置 D:\Pro\ytgis\src\Yt.Gis\X.App\Views\tiler\tdt.cs:行号 36
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\ytgis\src\Yt.Gis\X.Web\XApp.cs:行号 27
   --- 内部异常堆栈跟踪的结尾 ---

时间：2017-01-01 19:27:36,341 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\zfw\bw\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：105648623 
System.Exception: {"fg":"3","x":"26854","y":"14042","l":"15"} ---> System.Net.WebException: 未能解析此远程名称: 't3.tianditu.com'
   在 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   在 System.Net.WebClient.DownloadData(Uri address)
   在 System.Net.WebClient.DownloadData(String address)
   在 X.App.Views.tiler.tdt.GetResponse() 位置 D:\Pro\ytgis\src\Yt.Gis\X.App\Views\tiler\tdt.cs:行号 36
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\ytgis\src\Yt.Gis\X.Web\XApp.cs:行号 27
   --- 内部异常堆栈跟踪的结尾 ---

时间：2017-01-01 19:27:36,341 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\zfw\bw\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：105648623 
System.Exception: {"fg":"3","x":"12","y":"4","l":"4"} ---> System.Net.WebException: 未能解析此远程名称: 't3.tianditu.com'
   在 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   在 System.Net.WebClient.DownloadData(Uri address)
   在 System.Net.WebClient.DownloadData(String address)
   在 X.App.Views.tiler.tdt.GetResponse() 位置 D:\Pro\ytgis\src\Yt.Gis\X.App\Views\tiler\tdt.cs:行号 36
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\ytgis\src\Yt.Gis\X.Web\XApp.cs:行号 27
   --- 内部异常堆栈跟踪的结尾 ---

时间：2017-01-01 20:23:43,476 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\zfw\bw\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：495913 
System.Exception: {"fg":"2","x":"13437","y":"7025","l":"14"} ---> System.Net.WebException: 操作超时
   在 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   在 System.Net.WebClient.DownloadData(Uri address)
   在 System.Net.WebClient.DownloadData(String address)
   在 X.App.Views.tiler.tdt.GetResponse() 位置 D:\Pro\ytgis\src\Yt.Gis\X.App\Views\tiler\tdt.cs:行号 36
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\ytgis\src\Yt.Gis\X.Web\XApp.cs:行号 27
   --- 内部异常堆栈跟踪的结尾 ---

时间：2017-01-01 20:23:43,570 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\zfw\bw\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：496007 
System.Exception: {"fg":"5","x":"13436","y":"7024","l":"14"} ---> System.Net.WebException: 操作超时
   在 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   在 System.Net.WebClient.DownloadData(Uri address)
   在 System.Net.WebClient.DownloadData(String address)
   在 X.App.Views.tiler.tdt.GetResponse() 位置 D:\Pro\ytgis\src\Yt.Gis\X.App\Views\tiler\tdt.cs:行号 36
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\ytgis\src\Yt.Gis\X.Web\XApp.cs:行号 27
   --- 内部异常堆栈跟踪的结尾 ---

时间：2017-01-01 21:18:21,628 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\zfw\bw\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：3774065 
System.Exception: {"fg":"5","x":"12","y":"5","l":"4"} ---> System.Net.WebException: 操作超时
   在 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   在 System.Net.WebClient.DownloadData(Uri address)
   在 System.Net.WebClient.DownloadData(String address)
   在 X.App.Views.tiler.tdt.GetResponse() 位置 D:\Pro\ytgis\src\Yt.Gis\X.App\Views\tiler\tdt.cs:行号 36
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\ytgis\src\Yt.Gis\X.Web\XApp.cs:行号 27
   --- 内部异常堆栈跟踪的结尾 ---

时间：2017-01-01 21:22:28,984 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\zfw\bw\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：4021421 
System.Exception: {"fg":"5","x":"12","y":"5","l":"4"} ---> System.Net.WebException: 操作超时
   在 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   在 System.Net.WebClient.DownloadData(Uri address)
   在 System.Net.WebClient.DownloadData(String address)
   在 X.App.Views.tiler.tdt.GetResponse() 位置 D:\Pro\ytgis\src\Yt.Gis\X.App\Views\tiler\tdt.cs:行号 36
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\ytgis\src\Yt.Gis\X.Web\XApp.cs:行号 27
   --- 内部异常堆栈跟踪的结尾 ---

时间：2017-01-01 21:22:28,984 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\zfw\bw\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：4021421 
System.Exception: {"fg":"1","x":"12","y":"6","l":"4"} ---> System.Net.WebException: 操作超时
   在 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   在 System.Net.WebClient.DownloadData(Uri address)
   在 System.Net.WebClient.DownloadData(String address)
   在 X.App.Views.tiler.tdt.GetResponse() 位置 D:\Pro\ytgis\src\Yt.Gis\X.App\Views\tiler\tdt.cs:行号 36
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\ytgis\src\Yt.Gis\X.Web\XApp.cs:行号 27
   --- 内部异常堆栈跟踪的结尾 ---

时间：2017-01-01 21:22:28,984 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\zfw\bw\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：4021421 
System.Exception: {"fg":"3","x":"12","y":"4","l":"4"} ---> System.Net.WebException: 操作超时
   在 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   在 System.Net.WebClient.DownloadData(Uri address)
   在 System.Net.WebClient.DownloadData(String address)
   在 X.App.Views.tiler.tdt.GetResponse() 位置 D:\Pro\ytgis\src\Yt.Gis\X.App\Views\tiler\tdt.cs:行号 36
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\ytgis\src\Yt.Gis\X.Web\XApp.cs:行号 27
   --- 内部异常堆栈跟踪的结尾 ---

时间：2017-01-01 21:27:22,077 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\zfw\bw\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：4314514 
System.Exception: {"fg":"5","x":"215238","y":"110999","l":"18"} ---> System.Net.WebException: 操作超时
   在 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   在 System.Net.WebClient.DownloadData(Uri address)
   在 System.Net.WebClient.DownloadData(String address)
   在 X.App.Views.tiler.tdt.GetResponse() 位置 D:\Pro\ytgis\src\Yt.Gis\X.App\Views\tiler\tdt.cs:行号 36
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\ytgis\src\Yt.Gis\X.Web\XApp.cs:行号 27
   --- 内部异常堆栈跟踪的结尾 ---

时间：2017-01-01 21:27:22,185 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\zfw\bw\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：4314622 
System.Exception: {"fg":"5","x":"215236","y":"111000","l":"18"} ---> System.Net.WebException: 操作超时
   在 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   在 System.Net.WebClient.DownloadData(Uri address)
   在 System.Net.WebClient.DownloadData(String address)
   在 X.App.Views.tiler.tdt.GetResponse() 位置 D:\Pro\ytgis\src\Yt.Gis\X.App\Views\tiler\tdt.cs:行号 36
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\ytgis\src\Yt.Gis\X.Web\XApp.cs:行号 27
   --- 内部异常堆栈跟踪的结尾 ---

时间：2017-01-01 21:50:56,894 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\zfw\bw\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：5729331 
System.Exception: {"fg":"3","x":"215238","y":"110998","l":"18"} ---> System.Net.WebException: 无法连接到远程服务器 ---> System.Net.Sockets.SocketException: 由于目标计算机积极拒绝，无法连接。 1.202.227.113:80
   在 System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   在 System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   在 System.Net.WebClient.DownloadData(Uri address)
   在 System.Net.WebClient.DownloadData(String address)
   在 X.App.Views.tiler.tdt.GetResponse() 位置 D:\Pro\ytgis\src\Yt.Gis\X.App\Views\tiler\tdt.cs:行号 36
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\ytgis\src\Yt.Gis\X.Web\XApp.cs:行号 27
   --- 内部异常堆栈跟踪的结尾 ---

时间：2017-01-01 21:50:57,144 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\zfw\bw\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：5729581 
System.Exception: {"fg":"6","x":"215239","y":"110999","l":"18"} ---> System.Net.WebException: 无法连接到远程服务器 ---> System.Net.Sockets.SocketException: 由于目标计算机积极拒绝，无法连接。 1.202.227.113:80
   在 System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   在 System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   在 System.Net.WebClient.DownloadData(Uri address)
   在 System.Net.WebClient.DownloadData(String address)
   在 X.App.Views.tiler.tdt.GetResponse() 位置 D:\Pro\ytgis\src\Yt.Gis\X.App\Views\tiler\tdt.cs:行号 36
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\ytgis\src\Yt.Gis\X.Web\XApp.cs:行号 27
   --- 内部异常堆栈跟踪的结尾 ---

时间：2017-01-01 21:50:59,090 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\zfw\bw\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：5731527 
System.Exception: {"fg":"4","x":"215241","y":"110997","l":"18"} ---> System.Net.WebException: 无法连接到远程服务器 ---> System.Net.Sockets.SocketException: 由于目标计算机积极拒绝，无法连接。 1.202.227.113:80
   在 System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   在 System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   在 System.Net.WebClient.DownloadData(Uri address)
   在 System.Net.WebClient.DownloadData(String address)
   在 X.App.Views.tiler.tdt.GetResponse() 位置 D:\Pro\ytgis\src\Yt.Gis\X.App\Views\tiler\tdt.cs:行号 36
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\ytgis\src\Yt.Gis\X.Web\XApp.cs:行号 27
   --- 内部异常堆栈跟踪的结尾 ---

时间：2017-01-01 21:50:59,913 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\zfw\bw\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：5732350 
System.Exception: {"fg":"1","x":"215238","y":"111000","l":"18"} ---> System.Net.WebException: 无法连接到远程服务器 ---> System.Net.Sockets.SocketException: 由于目标计算机积极拒绝，无法连接。 1.202.227.113:80
   在 System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   在 System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   在 System.Net.WebClient.DownloadData(Uri address)
   在 System.Net.WebClient.DownloadData(String address)
   在 X.App.Views.tiler.tdt.GetResponse() 位置 D:\Pro\ytgis\src\Yt.Gis\X.App\Views\tiler\tdt.cs:行号 36
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\ytgis\src\Yt.Gis\X.Web\XApp.cs:行号 27
   --- 内部异常堆栈跟踪的结尾 ---

时间：2017-01-01 21:51:01,037 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\zfw\bw\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：5733474 
System.Exception: {"fg":"1","x":"215234","y":"110999","l":"18"} ---> System.Net.WebException: 无法连接到远程服务器 ---> System.Net.Sockets.SocketException: 由于目标计算机积极拒绝，无法连接。 1.202.227.113:80
   在 System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   在 System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   在 System.Net.WebClient.DownloadData(Uri address)
   在 System.Net.WebClient.DownloadData(String address)
   在 X.App.Views.tiler.tdt.GetResponse() 位置 D:\Pro\ytgis\src\Yt.Gis\X.App\Views\tiler\tdt.cs:行号 36
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\ytgis\src\Yt.Gis\X.Web\XApp.cs:行号 27
   --- 内部异常堆栈跟踪的结尾 ---

时间：2017-01-01 21:52:38,675 
级别：FATAL 
出错类：X.Web.XApp property: [(null)] 
出错位置：X.Core.Plugin.Loger.Fatal(D:\Pro\zfw\bw\src\Xc\Core\Plugin\Loger.cs:68) - 
错误：致命错误 
时间：5831112 
System.Exception: {"fg":"5","x":"215226","y":"110993","l":"18"} ---> System.Net.WebException: 操作超时
   在 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   在 System.Net.WebClient.DownloadData(Uri address)
   在 System.Net.WebClient.DownloadData(String address)
   在 X.App.Views.tiler.tdt.GetResponse() 位置 D:\Pro\ytgis\src\Yt.Gis\X.App\Views\tiler\tdt.cs:行号 36
   在 X.Web.XApp.ProcessRequest(HttpContext c) 位置 D:\Pro\ytgis\src\Yt.Gis\X.Web\XApp.cs:行号 27
   --- 内部异常堆栈跟踪的结尾 ---
